package seks.basic.db.hibernate;
// Generated 27/Dez/2011 14:33:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semanticvector generated by hbm2java
 */
@Entity
@Table(name="semanticvector"
    ,catalog="svdb"
)
public class Semanticvector  implements java.io.Serializable {


     private String documentUri;
     private String description;
     private Set<Semanticweight> semanticweights = new HashSet<Semanticweight>(0);

    public Semanticvector() {
    }

	
    public Semanticvector(String documentUri) {
        this.documentUri = documentUri;
    }
    public Semanticvector(String documentUri, String description, Set<Semanticweight> semanticweights) {
       this.documentUri = documentUri;
       this.description = description;
       this.semanticweights = semanticweights;
    }
   
     @Id 
    
    @Column(name="documentUri", unique=true, nullable=false, length=45)
    public String getDocumentUri() {
        return this.documentUri;
    }
    
    public void setDocumentUri(String documentUri) {
        this.documentUri = documentUri;
    }
    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="semanticvector")
    public Set<Semanticweight> getSemanticweights() {
        return this.semanticweights;
    }
    
    public void setSemanticweights(Set<Semanticweight> semanticweights) {
        this.semanticweights = semanticweights;
    }




}


