package seks.basic.db.hibernate;
// Generated 27/Dez/2011 14:33:27 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Semanticweight generated by hbm2java
 */
@Entity
@Table(name="semanticweight"
    ,catalog="svdb"
)
public class Semanticweight  implements java.io.Serializable {


     private SemanticweightId id;
     private Semanticvector semanticvector;
     private String parentClass;
     private String concept;
     private Integer weight;

    public Semanticweight() {
    }

	
    public Semanticweight(SemanticweightId id, Semanticvector semanticvector, String concept) {
        this.id = id;
        this.semanticvector = semanticvector;
        this.concept = concept;
    }
    public Semanticweight(SemanticweightId id, Semanticvector semanticvector, String parentClass, String concept, Integer weight) {
       this.id = id;
       this.semanticvector = semanticvector;
       this.parentClass = parentClass;
       this.concept = concept;
       this.weight = weight;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idSemanticWeight", column=@Column(name="idSemanticWeight", nullable=false) ), 
        @AttributeOverride(name="semanticVectorDocumentUri", column=@Column(name="SemanticVector_documentUri", nullable=false, length=45) ) } )
    public SemanticweightId getId() {
        return this.id;
    }
    
    public void setId(SemanticweightId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SemanticVector_documentUri", nullable=false, insertable=false, updatable=false)
    public Semanticvector getSemanticvector() {
        return this.semanticvector;
    }
    
    public void setSemanticvector(Semanticvector semanticvector) {
        this.semanticvector = semanticvector;
    }
    
    @Column(name="parentClass", length=45)
    public String getParentClass() {
        return this.parentClass;
    }
    
    public void setParentClass(String parentClass) {
        this.parentClass = parentClass;
    }
    
    @Column(name="concept", nullable=false, length=45)
    public String getConcept() {
        return this.concept;
    }
    
    public void setConcept(String concept) {
        this.concept = concept;
    }
    
    @Column(name="weight")
    public Integer getWeight() {
        return this.weight;
    }
    
    public void setWeight(Integer weight) {
        this.weight = weight;
    }




}


